services:
  - type: web
    name: auth-service
    runtime: node
    repo: https://github.com/Ben-Genius/auth-service.git
    branch: betterAuth
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        value: https://auth-service.onrender.com
      - key: NEXT_PUBLIC_BETTER_AUTH_URL
        value: https://auth-service.onrender.com
      - key: TRUSTED_ORIGINS
        value: https://auth-service.onrender.com
      - key: DATABASE_URL
        value: file:./prod.db
      - key: PORTAL_JWT_SECRET
        generateValue: true
      - key: SERVICE_JWT_SECRET
        generateValue: true
      - key: EMAIL_FROM
        value: Auth Service <azaygenius@gmail.com>
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: azaygenius@gmail.com
      - key: SMTP_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
